### ISSUE TITLE
SynapseError: 404 - Room alias #slack_TEAMNAME_XXX:MATRIXSERVER not found

### ISSUE THREAD

**Issue by DerBeutlin** [matrix-hacks/matrix-puppet-slack#73] opened 2019-01-18 17:20 UTC
I could not receive any slack messages in Matrix although the messages were received by the bridge. Instead I got the following error in the terminal
```
SynapseError: 404 - Room alias #slack_TEAMNAME_XXX:MATRIXSERVER not found
```

This got "fixed" by adding
```
  aliases:
    - exclusive: false
      regex: '#slack_.*:MATRIXSERVER'
```
to the `slack_registration.yaml`

**Comment by twouters** [comment] 2019-01-18 22:01
Just for reference, I've started seeing the following messages earlier this week for messages arriving from new Slack users or joining a new Slack room:

```
Tue, 15 Jan 2019 08:04:27 GMT matrix-puppet:slack:app This application service has not reserved this kind of alias.
[-] POST http://localhost:8008/_matrix/client/r0/createRoom (AS) HTTP 400 Error: {"errcode":"M_EXCLUSIVE","error":"This application service has not reserved this kind of alias."}
```
I think this change is the reason: https://github.com/matrix-org/synapse/pull/4063
Synapse now checks if the AS is allowed to create a room alias while it used to perform the check on the matrix user.

**Comment by twouters** [comment] 2019-01-18 23:50
Whoops, duplicate of #72 ?

**Closed** 2019-01-22 20:58 UTC
